### ISSUE TITLE
Install Git on the server(check description)

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#3]
Here's a tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-git-on-ubuntu-14-04

**Comment by githubERIK** [comment]
Executed the following commands in the server command line:
`sudo apt-get update`
`sudo apt-get install git`

**Comment by githubERIK** [comment]
Work includes: Reading the tutorial from issue description and acting according to that. 

Estimated: 0.1 man-hour
