### ISSUE TITLE
Create an about page

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#30]
The content should be dictated by the client.

See 1: https://github.com/vladislavivanistsev/SuperCap/wiki/_Functional%20requirements

Estimated 1 man-hour.

**Comment by AndreasGP** [comment]
The content should be dictated by the client.

**Comment by AndreasGP** [comment]
Estimated 1 man-hours.

**Comment by githubERIK** [comment]
Took 2 hours longer than expected, because added neccecary content as well.
