### ISSUE TITLE
Implement static 3D molecular model rendering

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#38]
Any static file can be used for this

See 3: https://github.com/vladislavivanistsev/SuperCap/wiki/_Functional%20requirements

Estimated 5 man-hours.

**Comment by AndreasGP** [comment]
Estimated 5 man-hours.

**Comment by KristjanP94** [comment]
3d model view area needs to scale.

**Comment by AndreasGP** [comment]
Closed for this iteration. Scalability task has been moved separate #68
