### ISSUE TITLE
Draw a single graph with correct calculations done

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#42]
See 4 ix: https://github.com/vladislavivanistsev/SuperCap/wiki/_Functional%20requirements

Estimated 3 man-hours

Related use cases: 
(https://github.com/vladislavivanistsev/SuperCap/wiki/_Use-Case:-Printing-the-graphs-selected-by-the-user) (https://github.com/vladislavivanistsev/SuperCap/wiki/_Use-Case:-Exporting-the-graphs-selected-by-the-user)

**Comment by AndreasGP** [comment]
Estimated 3 man-hours.

**Comment by githubERIK** [comment]
The functionality in the application covers at least one of the core use cases (peripheral use cases such as login/logout do not count towards being core use cases). The provided functionality is tested and works.

**Comment by githubERIK** [comment]
User can access the delivered functionality and test it's behaviour with minimal additional assistance.

**Comment by githubERIK** [comment]
The provided functionality is either bug-free or known bugs (which must not block the testing of the functionality) are registered in the issue tracker.

**Comment by AndreasGP** [comment]
Mainly done, integral calculations need fixing.See #75
