### ISSUE TITLE
Have someone external test the application usability

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#56]
See 7th requirement: https://github.com/vladislavivanistsev/SuperCap/wiki/_Non-functional%20requirements

Estimated 1 man-hour

**Comment by githubERIK** [comment]
Added [github.com/vladislavivanistsev/SuperCap/wiki/_NFR-verification/#user-content-monitoring-users-all-over-18] (github.com/vladislavivanistsev/SuperCap/wiki/_NFR-verification/#user-content-monitoring-users-all-over-18).
