### ISSUE TITLE
Describe local and live build process in the wiki.

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#59]
Write down the project  lcoal and live build process.

Estimated 1 man-hour.

**Comment by githubERIK** [comment]
Added detailed description for deploying to Heroku.
Commit [1721f31] (https://github.com/vladislavivanistsev/SuperCap/wiki/_Deployment/1721f31bbab46582ce565a0dea74ff42c3c45a2c)
Commit [07aed25] (https://github.com/vladislavivanistsev/SuperCap/wiki/_Deployment/07aed25682b2ac710856614b0ba149352deae00c)

[Up-to-date page] (https://github.com/vladislavivanistsev/SuperCap/wiki/_Deployment)
