### ISSUE TITLE
Issue: No nodejs plugin available on certain netbeans versions

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#84]
The installation wiki should include details how to manually install the node.js plugin for netbeans from http://plugins.netbeans.org/plugin/36653/nodejs

**Comment by githubERIK** [comment]
Added text:
Please download NodeJS plugin from "Available Plugins" tab and add it to Netbeans from "Downloaded" tab in Netbeans plugin menu.
If you have problems with this plugin and Netbeans please download it manually: http://plugins.netbeans.org/plugin/36653/nodejs.
