### ISSUE TITLE
Set up node.js and mongoDB

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#9]

**Comment by githubERIK** [comment]
Initial Skeleton Code set these things up.
Commit: [334f9cf] (https://github.com/vladislavivanistsev/SuperCap/commit/334f9cfa9c73934982a07c5f1aac5aee59fe55c3)

**Comment by githubERIK** [comment]
Work includes: Getting familiar and also implementing simple database operation to see how that works. 

Estimated: 3 man-hours
