### ISSUE TITLE
Update customer meeting notes for 06.11 meeting

### ISSUE THREAD

**Issue by AndreasGP** [vladislavivanistsev/SuperCap#90]
Self-explainatory

Estimated 1 man-hour.

**Comment by githubERIK** [comment]
Done. Check out the 4th meeting report:
[https://github.com/vladislavivanistsev/SuperCap/wiki/Customer-Meetings] (https://github.com/vladislavivanistsev/SuperCap/wiki/Customer-Meetings) .
